services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: lrizkitegar/flowchart-maker
    container_name: flowchart-server
    volumes:
      - data:/storage
    ports:
      - "9612:80"
volumes:
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./storage